services:
  whisper-server:
    image: ${WHISPER_IMAGE:-ml-openai-whisper:latest}
    pull_policy: always
    container_name: whisper-server
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs
      - whisper_cache:/root/.cache
    restart: unless-stopped

volumes:
  whisper_cache:
